# Generated by Django 6.0.3 on 2026-04-04 17:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('gateway', models.CharField(choices=[('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('account_name', models.CharField(blank=True, max_length=150)),
                ('gateway_txn_id', models.CharField(blank=True, max_length=100)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending Verification'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
